version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "Europe/Bratislava"
    open-pull-requests-limit: 10
    groups:
      production-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      security:
        patterns:
          - "*"
        update-types:
          - "security"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"