name: ci
on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  quality-checks:
    name: Frontend checks
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install packages
        run: npm ci

      - name: NPM security audit
        run: npm audit --audit-level=critical

      - name: Run Lint
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run unit tests
        run: npm run vitest
        env:
          CI: true

      - name: Build app
        run: npm run build
